# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyVakitci.ui'
#
# Created: Sat Mar  7 22:36:11 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4 import phonon
import moduller.PyVakitci_rc

def _fromUtf8(s):
    return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(351, 511)
        MainWindow.setMinimumSize(QtCore.QSize(351, 511))
        MainWindow.setMaximumSize(QtCore.QSize(351, 511))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resimler/cami.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 330, 441))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(310, 441))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setIconSize(QtCore.QSize(38, 38))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.pyvakitci_tab = QtGui.QWidget()
        self.pyvakitci_tab.setObjectName(_fromUtf8("pyvakitci_tab"))
        self.bilgiler_groupBox = QtGui.QGroupBox(self.pyvakitci_tab)
        self.bilgiler_groupBox.setEnabled(True)
        self.bilgiler_groupBox.setGeometry(QtCore.QRect(13, 12, 301, 64))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.bilgiler_groupBox.setFont(font)
        self.bilgiler_groupBox.setTitle(_fromUtf8(""))
        self.bilgiler_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bilgiler_groupBox.setFlat(False)
        self.bilgiler_groupBox.setCheckable(False)
        self.bilgiler_groupBox.setChecked(False)
        self.bilgiler_groupBox.setObjectName(_fromUtf8("bilgiler_groupBox"))
        self.ulke_label = QtGui.QLabel(self.bilgiler_groupBox)
        self.ulke_label.setGeometry(QtCore.QRect(10, 10, 150, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ulke_label.setFont(font)
        self.ulke_label.setObjectName(_fromUtf8("ulke_label"))
        self.sehir_label = QtGui.QLabel(self.bilgiler_groupBox)
        self.sehir_label.setGeometry(QtCore.QRect(10, 40, 160, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.sehir_label.setFont(font)
        self.sehir_label.setObjectName(_fromUtf8("sehir_label"))
        self.miladi_tarih = QtGui.QLabel(self.bilgiler_groupBox)
        self.miladi_tarih.setGeometry(QtCore.QRect(198, 10, 98, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.miladi_tarih.setFont(font)
        self.miladi_tarih.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.miladi_tarih.setObjectName(_fromUtf8("miladi_tarih"))
        self.hicri_tarih = QtGui.QLabel(self.bilgiler_groupBox)
        self.hicri_tarih.setGeometry(QtCore.QRect(156, 25, 140, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hicri_tarih.setFont(font)
        self.hicri_tarih.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hicri_tarih.setObjectName(_fromUtf8("hicri_tarih"))
        self.saat_label = QtGui.QLabel(self.bilgiler_groupBox)
        self.saat_label.setGeometry(QtCore.QRect(204, 40, 92, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.saat_label.setFont(font)
        self.saat_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.saat_label.setObjectName(_fromUtf8("saat_label"))
        self.namaz_vakitleri_groupBox = QtGui.QGroupBox(self.pyvakitci_tab)
        self.namaz_vakitleri_groupBox.setGeometry(QtCore.QRect(13, 84, 301, 301))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.namaz_vakitleri_groupBox.setFont(font)
        self.namaz_vakitleri_groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.namaz_vakitleri_groupBox.setTitle(_fromUtf8(""))
        self.namaz_vakitleri_groupBox.setObjectName(_fromUtf8("namaz_vakitleri_groupBox"))
        self.namaz_vakti_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.namaz_vakti_label.setGeometry(QtCore.QRect(10, 15, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.namaz_vakti_label.setFont(font)
        self.namaz_vakti_label.setAlignment(QtCore.Qt.AlignCenter)
        self.namaz_vakti_label.setObjectName(_fromUtf8("namaz_vakti_label"))
        self.line = QtGui.QFrame(self.namaz_vakitleri_groupBox)
        self.line.setGeometry(QtCore.QRect(40, 30, 221, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(221, 16))
        self.line.setMaximumSize(QtCore.QSize(221, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.imsak_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.imsak_label.setGeometry(QtCore.QRect(92, 55, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.imsak_label.setFont(font)
        self.imsak_label.setObjectName(_fromUtf8("imsak_label"))
        self.gunes_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.gunes_label.setGeometry(QtCore.QRect(92, 85, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.gunes_label.setFont(font)
        self.gunes_label.setObjectName(_fromUtf8("gunes_label"))
        self.ogle_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ogle_label.setGeometry(QtCore.QRect(92, 115, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ogle_label.setFont(font)
        self.ogle_label.setObjectName(_fromUtf8("ogle_label"))
        self.ikindi_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ikindi_label.setGeometry(QtCore.QRect(92, 145, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ikindi_label.setFont(font)
        self.ikindi_label.setObjectName(_fromUtf8("ikindi_label"))
        self.aksam_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.aksam_label.setGeometry(QtCore.QRect(92, 175, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aksam_label.setFont(font)
        self.aksam_label.setObjectName(_fromUtf8("aksam_label"))
        self.yatsi_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.yatsi_label.setGeometry(QtCore.QRect(92, 205, 50, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.yatsi_label.setFont(font)
        self.yatsi_label.setObjectName(_fromUtf8("yatsi_label"))
        self.nokta_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label.setGeometry(QtCore.QRect(152, 57, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nokta_label.setFont(font)
        self.nokta_label.setObjectName(_fromUtf8("nokta_label"))
        self.nokta_label_2 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_2.setGeometry(QtCore.QRect(152, 87, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nokta_label_2.setFont(font)
        self.nokta_label_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.nokta_label_2.setObjectName(_fromUtf8("nokta_label_2"))
        self.nokta_label_3 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_3.setGeometry(QtCore.QRect(152, 117, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nokta_label_3.setFont(font)
        self.nokta_label_3.setObjectName(_fromUtf8("nokta_label_3"))
        self.nokta_label_4 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_4.setGeometry(QtCore.QRect(152, 147, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nokta_label_4.setFont(font)
        self.nokta_label_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.nokta_label_4.setObjectName(_fromUtf8("nokta_label_4"))
        self.nokta_label_5 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_5.setGeometry(QtCore.QRect(152, 177, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nokta_label_5.setFont(font)
        self.nokta_label_5.setObjectName(_fromUtf8("nokta_label_5"))
        self.nokta_label_6 = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.nokta_label_6.setGeometry(QtCore.QRect(152, 207, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.nokta_label_6.setFont(font)
        self.nokta_label_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.nokta_label_6.setObjectName(_fromUtf8("nokta_label_6"))
        self.imsak_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.imsak_saat_label.setGeometry(QtCore.QRect(172, 58, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.imsak_saat_label.setFont(font)
        self.imsak_saat_label.setObjectName(_fromUtf8("imsak_saat_label"))
        self.gunes_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.gunes_saat_label.setGeometry(QtCore.QRect(172, 88, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.gunes_saat_label.setFont(font)
        self.gunes_saat_label.setObjectName(_fromUtf8("gunes_saat_label"))
        self.ogle_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ogle_saat_label.setGeometry(QtCore.QRect(172, 118, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ogle_saat_label.setFont(font)
        self.ogle_saat_label.setObjectName(_fromUtf8("ogle_saat_label"))
        self.ikindi_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.ikindi_saat_label.setGeometry(QtCore.QRect(172, 148, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.ikindi_saat_label.setFont(font)
        self.ikindi_saat_label.setObjectName(_fromUtf8("ikindi_saat_label"))
        self.aksam_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.aksam_saat_label.setGeometry(QtCore.QRect(172, 178, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.aksam_saat_label.setFont(font)
        self.aksam_saat_label.setObjectName(_fromUtf8("aksam_saat_label"))
        self.yatsi_saat_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.yatsi_saat_label.setGeometry(QtCore.QRect(172, 208, 50, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.yatsi_saat_label.setFont(font)
        self.yatsi_saat_label.setObjectName(_fromUtf8("yatsi_saat_label"))
        self.sonraki_vakit_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.sonraki_vakit_label.setGeometry(QtCore.QRect(95, 235, 130, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.sonraki_vakit_label.setFont(font)
        self.sonraki_vakit_label.setObjectName(_fromUtf8("sonraki_vakit_label"))
        self.kalan_sure_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.kalan_sure_label.setGeometry(QtCore.QRect(120, 255, 120, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.kalan_sure_label.setFont(font)
        self.kalan_sure_label.setObjectName(_fromUtf8("kalan_sure_label"))
        self.dini_gun_label = QtGui.QLabel(self.namaz_vakitleri_groupBox)
        self.dini_gun_label.setGeometry(QtCore.QRect(10, 275, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.dini_gun_label.setFont(font)
        self.dini_gun_label.setText(_fromUtf8(""))
        self.dini_gun_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dini_gun_label.setObjectName(_fromUtf8("dini_gun_label"))
        self.tabWidget.addTab(self.pyvakitci_tab, icon, _fromUtf8(""))
        self.bolgesel_ayarlar_tab = QtGui.QWidget()
        self.bolgesel_ayarlar_tab.setObjectName(_fromUtf8("bolgesel_ayarlar_tab"))
        self.bolgesel_ayarlar_groupBox = QtGui.QGroupBox(self.bolgesel_ayarlar_tab)
        self.bolgesel_ayarlar_groupBox.setGeometry(QtCore.QRect(13, 4, 301, 381))
        self.bolgesel_ayarlar_groupBox.setMinimumSize(QtCore.QSize(280, 381))
        self.bolgesel_ayarlar_groupBox.setObjectName(_fromUtf8("bolgesel_ayarlar_groupBox"))
        self.bolgesel_ayarlar_ulke_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_ulke_label.setGeometry(QtCore.QRect(15, 35, 71, 17))
        self.bolgesel_ayarlar_ulke_label.setObjectName(_fromUtf8("bolgesel_ayarlar_ulke_label"))
        self.ulkeler_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.ulkeler_comboBox.setGeometry(QtCore.QRect(80, 30, 200, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ulkeler_comboBox.sizePolicy().hasHeightForWidth())
        self.ulkeler_comboBox.setSizePolicy(sizePolicy)
        self.ulkeler_comboBox.setObjectName(_fromUtf8("ulkeler_comboBox"))
        self.bolgesel_ayarlar_sehir_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_sehir_label.setGeometry(QtCore.QRect(15, 75, 71, 17))
        self.bolgesel_ayarlar_sehir_label.setObjectName(_fromUtf8("bolgesel_ayarlar_sehir_label"))
        self.sehirler_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.sehirler_comboBox.setGeometry(QtCore.QRect(80, 70, 200, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sehirler_comboBox.sizePolicy().hasHeightForWidth())
        self.sehirler_comboBox.setSizePolicy(sizePolicy)
        self.sehirler_comboBox.setObjectName(_fromUtf8("sehirler_comboBox"))
        self.bolgesel_ayarlar_kaydet_pushButton = QtGui.QPushButton(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_kaydet_pushButton.setGeometry(QtCore.QRect(200, 345, 85, 28))
        self.bolgesel_ayarlar_kaydet_pushButton.setObjectName(_fromUtf8("bolgesel_ayarlar_kaydet_pushButton"))
        self.bolgesel_ayarlar_varsayilan_pushButton = QtGui.QPushButton(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_varsayilan_pushButton.setGeometry(QtCore.QRect(110, 345, 85, 28))
        self.bolgesel_ayarlar_varsayilan_pushButton.setObjectName(_fromUtf8("bolgesel_ayarlar_varsayilan_pushButton"))
        self.ilceler_comboBox = QtGui.QComboBox(self.bolgesel_ayarlar_groupBox)
        self.ilceler_comboBox.setEnabled(False)
        self.ilceler_comboBox.setGeometry(QtCore.QRect(80, 110, 200, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ilceler_comboBox.sizePolicy().hasHeightForWidth())
        self.ilceler_comboBox.setSizePolicy(sizePolicy)
        self.ilceler_comboBox.setObjectName(_fromUtf8("ilceler_comboBox"))
        self.bolgesel_ayarlar_ilce_label = QtGui.QLabel(self.bolgesel_ayarlar_groupBox)
        self.bolgesel_ayarlar_ilce_label.setGeometry(QtCore.QRect(15, 115, 71, 17))
        self.bolgesel_ayarlar_ilce_label.setObjectName(_fromUtf8("bolgesel_ayarlar_ilce_label"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/resimler/world.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.bolgesel_ayarlar_tab, icon1, _fromUtf8(""))
        self.ayarlar_tab = QtGui.QWidget()
        self.ayarlar_tab.setObjectName(_fromUtf8("ayarlar_tab"))
        self.ayarlar_groupBox = QtGui.QGroupBox(self.ayarlar_tab)
        self.ayarlar_groupBox.setGeometry(QtCore.QRect(13, 4, 301, 381))
        self.ayarlar_groupBox.setMinimumSize(QtCore.QSize(280, 381))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ayarlar_groupBox.setFont(font)
        self.ayarlar_groupBox.setFlat(False)
        self.ayarlar_groupBox.setObjectName(_fromUtf8("ayarlar_groupBox"))
        self.otomatik_calistir_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.otomatik_calistir_checkBox.setGeometry(QtCore.QRect(10, 25, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otomatik_calistir_checkBox.sizePolicy().hasHeightForWidth())
        self.otomatik_calistir_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.otomatik_calistir_checkBox.setFont(font)
        self.otomatik_calistir_checkBox.setObjectName(_fromUtf8("otomatik_calistir_checkBox"))
        self.her_zaman_ustte_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.her_zaman_ustte_checkBox.setGeometry(QtCore.QRect(10, 125, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.her_zaman_ustte_checkBox.sizePolicy().hasHeightForWidth())
        self.her_zaman_ustte_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.her_zaman_ustte_checkBox.setFont(font)
        self.her_zaman_ustte_checkBox.setObjectName(_fromUtf8("her_zaman_ustte_checkBox"))
        self.erken_uyari_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.erken_uyari_checkBox.setGeometry(QtCore.QRect(10, 200, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erken_uyari_checkBox.sizePolicy().hasHeightForWidth())
        self.erken_uyari_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.erken_uyari_checkBox.setFont(font)
        self.erken_uyari_checkBox.setObjectName(_fromUtf8("erken_uyari_checkBox"))
        self.ayarlar_kaydet_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.ayarlar_kaydet_pushButton.setGeometry(QtCore.QRect(200, 345, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ayarlar_kaydet_pushButton.setFont(font)
        self.ayarlar_kaydet_pushButton.setObjectName(_fromUtf8("ayarlar_kaydet_pushButton"))
        self.ayarlar_varsayilan_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.ayarlar_varsayilan_pushButton.setGeometry(QtCore.QRect(110, 345, 85, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ayarlar_varsayilan_pushButton.setFont(font)
        self.ayarlar_varsayilan_pushButton.setObjectName(_fromUtf8("ayarlar_varsayilan_pushButton"))
        self.besmele_ile_basla_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.besmele_ile_basla_checkBox.setGeometry(QtCore.QRect(10, 150, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.besmele_ile_basla_checkBox.sizePolicy().hasHeightForWidth())
        self.besmele_ile_basla_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.besmele_ile_basla_checkBox.setFont(font)
        self.besmele_ile_basla_checkBox.setObjectName(_fromUtf8("besmele_ile_basla_checkBox"))
        self.otomatik_guncellestir_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.otomatik_guncellestir_checkBox.setGeometry(QtCore.QRect(10, 100, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otomatik_guncellestir_checkBox.sizePolicy().hasHeightForWidth())
        self.otomatik_guncellestir_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.otomatik_guncellestir_checkBox.setFont(font)
        self.otomatik_guncellestir_checkBox.setObjectName(_fromUtf8("otomatik_guncellestir_checkBox"))
        self.sistem_tepsisinde_baslat_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.sistem_tepsisinde_baslat_checkBox.setGeometry(QtCore.QRect(10, 75, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sistem_tepsisinde_baslat_checkBox.sizePolicy().hasHeightForWidth())
        self.sistem_tepsisinde_baslat_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sistem_tepsisinde_baslat_checkBox.setFont(font)
        self.sistem_tepsisinde_baslat_checkBox.setObjectName(_fromUtf8("sistem_tepsisinde_baslat_checkBox"))
        self.vakitleri_goster_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.vakitleri_goster_pushButton.setGeometry(QtCore.QRect(21, 275, 263, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vakitleri_goster_pushButton.setFont(font)
        self.vakitleri_goster_pushButton.setObjectName(_fromUtf8("vakitleri_goster_pushButton"))
        self.vakitleri_guncelle_pushButton = QtGui.QPushButton(self.ayarlar_groupBox)
        self.vakitleri_guncelle_pushButton.setGeometry(QtCore.QRect(21, 310, 263, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.vakitleri_guncelle_pushButton.setFont(font)
        self.vakitleri_guncelle_pushButton.setObjectName(_fromUtf8("vakitleri_guncelle_pushButton"))
        self.erken_uyari_sela_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.erken_uyari_sela_checkBox.setGeometry(QtCore.QRect(10, 225, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.erken_uyari_sela_checkBox.sizePolicy().hasHeightForWidth())
        self.erken_uyari_sela_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.erken_uyari_sela_checkBox.setFont(font)
        self.erken_uyari_sela_checkBox.setObjectName(_fromUtf8("erken_uyari_sela_checkBox"))
        self.erken_uyari_sela_spinBox = QtGui.QSpinBox(self.ayarlar_groupBox)
        self.erken_uyari_sela_spinBox.setGeometry(QtCore.QRect(240, 226, 42, 22))
        self.erken_uyari_sela_spinBox.setMinimum(0)
        self.erken_uyari_sela_spinBox.setMaximum(120)
        self.erken_uyari_sela_spinBox.setProperty("value", 55)
        self.erken_uyari_sela_spinBox.setObjectName(_fromUtf8("erken_uyari_sela_spinBox"))
        self.erken_uyari_spinBox = QtGui.QSpinBox(self.ayarlar_groupBox)
        self.erken_uyari_spinBox.setGeometry(QtCore.QRect(240, 201, 42, 22))
        self.erken_uyari_spinBox.setMinimum(0)
        self.erken_uyari_spinBox.setProperty("value", 45)
        self.erken_uyari_spinBox.setObjectName(_fromUtf8("erken_uyari_spinBox"))
        self.hicri_gun_ekle_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.hicri_gun_ekle_checkBox.setGeometry(QtCore.QRect(10, 250, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hicri_gun_ekle_checkBox.sizePolicy().hasHeightForWidth())
        self.hicri_gun_ekle_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hicri_gun_ekle_checkBox.setFont(font)
        self.hicri_gun_ekle_checkBox.setObjectName(_fromUtf8("hicri_gun_ekle_checkBox"))
        self.ikon_goster_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.ikon_goster_checkBox.setGeometry(QtCore.QRect(10, 50, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ikon_goster_checkBox.sizePolicy().hasHeightForWidth())
        self.ikon_goster_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ikon_goster_checkBox.setFont(font)
        self.ikon_goster_checkBox.setObjectName(_fromUtf8("ikon_goster_checkBox"))
        self.winamp_duraklat_checkBox = QtGui.QCheckBox(self.ayarlar_groupBox)
        self.winamp_duraklat_checkBox.setGeometry(QtCore.QRect(10, 175, 285, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.winamp_duraklat_checkBox.sizePolicy().hasHeightForWidth())
        self.winamp_duraklat_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.winamp_duraklat_checkBox.setFont(font)
        self.winamp_duraklat_checkBox.setObjectName(_fromUtf8("winamp_duraklat_checkBox"))
        self.hicri_tarih_gun_ekle_spinBox = QtGui.QSpinBox(self.ayarlar_groupBox)
        self.hicri_tarih_gun_ekle_spinBox.setGeometry(QtCore.QRect(240, 250, 42, 22))
        self.hicri_tarih_gun_ekle_spinBox.setMinimum(-1)
        self.hicri_tarih_gun_ekle_spinBox.setMaximum(1)
        self.hicri_tarih_gun_ekle_spinBox.setObjectName(_fromUtf8("hicri_tarih_gun_ekle_spinBox"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/resimler/ayarlar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ayarlar_tab, icon2, _fromUtf8(""))
        self.ses_dosyalari_tab = QtGui.QWidget()
        self.ses_dosyalari_tab.setObjectName(_fromUtf8("ses_dosyalari_tab"))
        self.sabah_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.sabah_ses_label.setGeometry(QtCore.QRect(10, 20, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sabah_ses_label.setFont(font)
        self.sabah_ses_label.setObjectName(_fromUtf8("sabah_ses_label"))
        self.sabah_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.sabah_lineEdit.setGeometry(QtCore.QRect(70, 17, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sabah_lineEdit.sizePolicy().hasHeightForWidth())
        self.sabah_lineEdit.setSizePolicy(sizePolicy)
        self.sabah_lineEdit.setReadOnly(True)
        self.sabah_lineEdit.setObjectName(_fromUtf8("sabah_lineEdit"))
        self.sabah_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.sabah_toolButton.setGeometry(QtCore.QRect(240, 18, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sabah_toolButton.sizePolicy().hasHeightForWidth())
        self.sabah_toolButton.setSizePolicy(sizePolicy)
        self.sabah_toolButton.setObjectName(_fromUtf8("sabah_toolButton"))
        self.dua_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.dua_toolButton.setGeometry(QtCore.QRect(240, 208, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dua_toolButton.sizePolicy().hasHeightForWidth())
        self.dua_toolButton.setSizePolicy(sizePolicy)
        self.dua_toolButton.setObjectName(_fromUtf8("dua_toolButton"))
        self.dua_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.dua_ses_label.setGeometry(QtCore.QRect(10, 210, 70, 17))
        self.dua_ses_label.setObjectName(_fromUtf8("dua_ses_label"))
        self.aksam_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.aksam_ses_label.setGeometry(QtCore.QRect(10, 134, 70, 17))
        self.aksam_ses_label.setObjectName(_fromUtf8("aksam_ses_label"))
        self.aksam_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.aksam_lineEdit.setGeometry(QtCore.QRect(70, 131, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aksam_lineEdit.sizePolicy().hasHeightForWidth())
        self.aksam_lineEdit.setSizePolicy(sizePolicy)
        self.aksam_lineEdit.setReadOnly(True)
        self.aksam_lineEdit.setObjectName(_fromUtf8("aksam_lineEdit"))
        self.aksam_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.aksam_toolButton.setGeometry(QtCore.QRect(240, 132, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aksam_toolButton.sizePolicy().hasHeightForWidth())
        self.aksam_toolButton.setSizePolicy(sizePolicy)
        self.aksam_toolButton.setObjectName(_fromUtf8("aksam_toolButton"))
        self.uyari_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.uyari_toolButton.setGeometry(QtCore.QRect(240, 288, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uyari_toolButton.sizePolicy().hasHeightForWidth())
        self.uyari_toolButton.setSizePolicy(sizePolicy)
        self.uyari_toolButton.setObjectName(_fromUtf8("uyari_toolButton"))
        self.yatsi_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.yatsi_ses_label.setGeometry(QtCore.QRect(10, 172, 70, 17))
        self.yatsi_ses_label.setObjectName(_fromUtf8("yatsi_ses_label"))
        self.yatsi_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.yatsi_lineEdit.setGeometry(QtCore.QRect(70, 169, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yatsi_lineEdit.sizePolicy().hasHeightForWidth())
        self.yatsi_lineEdit.setSizePolicy(sizePolicy)
        self.yatsi_lineEdit.setReadOnly(True)
        self.yatsi_lineEdit.setObjectName(_fromUtf8("yatsi_lineEdit"))
        self.yatsi_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.yatsi_toolButton.setGeometry(QtCore.QRect(240, 170, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yatsi_toolButton.sizePolicy().hasHeightForWidth())
        self.yatsi_toolButton.setSizePolicy(sizePolicy)
        self.yatsi_toolButton.setObjectName(_fromUtf8("yatsi_toolButton"))
        self.uyari_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.uyari_ses_label.setGeometry(QtCore.QRect(10, 290, 70, 17))
        self.uyari_ses_label.setObjectName(_fromUtf8("uyari_ses_label"))
        self.ogle_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.ogle_ses_label.setGeometry(QtCore.QRect(10, 58, 70, 17))
        self.ogle_ses_label.setObjectName(_fromUtf8("ogle_ses_label"))
        self.ogle_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.ogle_lineEdit.setGeometry(QtCore.QRect(70, 55, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ogle_lineEdit.sizePolicy().hasHeightForWidth())
        self.ogle_lineEdit.setSizePolicy(sizePolicy)
        self.ogle_lineEdit.setReadOnly(True)
        self.ogle_lineEdit.setObjectName(_fromUtf8("ogle_lineEdit"))
        self.ogle_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.ogle_toolButton.setGeometry(QtCore.QRect(240, 56, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ogle_toolButton.sizePolicy().hasHeightForWidth())
        self.ogle_toolButton.setSizePolicy(sizePolicy)
        self.ogle_toolButton.setObjectName(_fromUtf8("ogle_toolButton"))
        self.uyari_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.uyari_lineEdit.setGeometry(QtCore.QRect(70, 287, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uyari_lineEdit.sizePolicy().hasHeightForWidth())
        self.uyari_lineEdit.setSizePolicy(sizePolicy)
        self.uyari_lineEdit.setReadOnly(True)
        self.uyari_lineEdit.setObjectName(_fromUtf8("uyari_lineEdit"))
        self.dua_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.dua_lineEdit.setGeometry(QtCore.QRect(70, 207, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dua_lineEdit.sizePolicy().hasHeightForWidth())
        self.dua_lineEdit.setSizePolicy(sizePolicy)
        self.dua_lineEdit.setReadOnly(True)
        self.dua_lineEdit.setObjectName(_fromUtf8("dua_lineEdit"))
        self.ikindi_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.ikindi_ses_label.setGeometry(QtCore.QRect(10, 96, 70, 17))
        self.ikindi_ses_label.setObjectName(_fromUtf8("ikindi_ses_label"))
        self.ikindi_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.ikindi_lineEdit.setGeometry(QtCore.QRect(70, 93, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ikindi_lineEdit.sizePolicy().hasHeightForWidth())
        self.ikindi_lineEdit.setSizePolicy(sizePolicy)
        self.ikindi_lineEdit.setReadOnly(True)
        self.ikindi_lineEdit.setObjectName(_fromUtf8("ikindi_lineEdit"))
        self.ikindi_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.ikindi_toolButton.setGeometry(QtCore.QRect(240, 94, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ikindi_toolButton.sizePolicy().hasHeightForWidth())
        self.ikindi_toolButton.setSizePolicy(sizePolicy)
        self.ikindi_toolButton.setObjectName(_fromUtf8("ikindi_toolButton"))
        self.ses_kaydet_pushButton = QtGui.QPushButton(self.ses_dosyalari_tab)
        self.ses_kaydet_pushButton.setGeometry(QtCore.QRect(230, 350, 85, 28))
        self.ses_kaydet_pushButton.setObjectName(_fromUtf8("ses_kaydet_pushButton"))
        self.ses_varsayilan_pushButton = QtGui.QPushButton(self.ses_dosyalari_tab)
        self.ses_varsayilan_pushButton.setGeometry(QtCore.QRect(140, 350, 85, 28))
        self.ses_varsayilan_pushButton.setObjectName(_fromUtf8("ses_varsayilan_pushButton"))
        self.sela_lineEdit = QtGui.QLineEdit(self.ses_dosyalari_tab)
        self.sela_lineEdit.setGeometry(QtCore.QRect(70, 247, 160, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sela_lineEdit.sizePolicy().hasHeightForWidth())
        self.sela_lineEdit.setSizePolicy(sizePolicy)
        self.sela_lineEdit.setReadOnly(True)
        self.sela_lineEdit.setObjectName(_fromUtf8("sela_lineEdit"))
        self.sela_ses_label = QtGui.QLabel(self.ses_dosyalari_tab)
        self.sela_ses_label.setGeometry(QtCore.QRect(10, 250, 70, 17))
        self.sela_ses_label.setObjectName(_fromUtf8("sela_ses_label"))
        self.sela_toolButton = QtGui.QToolButton(self.ses_dosyalari_tab)
        self.sela_toolButton.setGeometry(QtCore.QRect(240, 248, 40, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sela_toolButton.sizePolicy().hasHeightForWidth())
        self.sela_toolButton.setSizePolicy(sizePolicy)
        self.sela_toolButton.setObjectName(_fromUtf8("sela_toolButton"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.ses_dosyalari_tab)
        self.volumeSlider.setGeometry(QtCore.QRect(195, 315, 115, 22))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.sabah_ezani_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.sabah_ezani_oku_checkBox.setGeometry(QtCore.QRect(295, 20, 21, 20))
        self.sabah_ezani_oku_checkBox.setText(_fromUtf8(""))
        self.sabah_ezani_oku_checkBox.setObjectName(_fromUtf8("sabah_ezani_oku_checkBox"))
        self.ogle_ezani_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.ogle_ezani_oku_checkBox.setGeometry(QtCore.QRect(295, 58, 21, 20))
        self.ogle_ezani_oku_checkBox.setText(_fromUtf8(""))
        self.ogle_ezani_oku_checkBox.setObjectName(_fromUtf8("ogle_ezani_oku_checkBox"))
        self.ikindi_ezani_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.ikindi_ezani_oku_checkBox.setGeometry(QtCore.QRect(295, 96, 21, 20))
        self.ikindi_ezani_oku_checkBox.setText(_fromUtf8(""))
        self.ikindi_ezani_oku_checkBox.setObjectName(_fromUtf8("ikindi_ezani_oku_checkBox"))
        self.aksam_ezani_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.aksam_ezani_oku_checkBox.setGeometry(QtCore.QRect(295, 134, 21, 20))
        self.aksam_ezani_oku_checkBox.setText(_fromUtf8(""))
        self.aksam_ezani_oku_checkBox.setObjectName(_fromUtf8("aksam_ezani_oku_checkBox"))
        self.yatsi_ezani_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.yatsi_ezani_oku_checkBox.setGeometry(QtCore.QRect(295, 172, 21, 20))
        self.yatsi_ezani_oku_checkBox.setText(_fromUtf8(""))
        self.yatsi_ezani_oku_checkBox.setObjectName(_fromUtf8("yatsi_ezani_oku_checkBox"))
        self.dua_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.dua_oku_checkBox.setGeometry(QtCore.QRect(295, 210, 21, 20))
        self.dua_oku_checkBox.setText(_fromUtf8(""))
        self.dua_oku_checkBox.setObjectName(_fromUtf8("dua_oku_checkBox"))
        self.sela_oku_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.sela_oku_checkBox.setGeometry(QtCore.QRect(295, 250, 21, 20))
        self.sela_oku_checkBox.setText(_fromUtf8(""))
        self.sela_oku_checkBox.setObjectName(_fromUtf8("sela_oku_checkBox"))
        self.uyari_sesi_checkBox = QtGui.QCheckBox(self.ses_dosyalari_tab)
        self.uyari_sesi_checkBox.setGeometry(QtCore.QRect(295, 290, 21, 20))
        self.uyari_sesi_checkBox.setText(_fromUtf8(""))
        self.uyari_sesi_checkBox.setObjectName(_fromUtf8("uyari_sesi_checkBox"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/resimler/ses_dosyalari.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.ses_dosyalari_tab, icon3, _fromUtf8(""))
        self.linkler_tab = QtGui.QWidget()
        self.linkler_tab.setObjectName(_fromUtf8("linkler_tab"))
        self.linkler_groupBox = QtGui.QGroupBox(self.linkler_tab)
        self.linkler_groupBox.setGeometry(QtCore.QRect(13, 4, 301, 381))
        self.linkler_groupBox.setObjectName(_fromUtf8("linkler_groupBox"))
        self.site_01_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_01_label.setGeometry(QtCore.QRect(15, 20, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_01_label.sizePolicy().hasHeightForWidth())
        self.site_01_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.site_01_label.setFont(font)
        self.site_01_label.setOpenExternalLinks(True)
        self.site_01_label.setObjectName(_fromUtf8("site_01_label"))
        self.site_05_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_05_label.setGeometry(QtCore.QRect(15, 80, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_05_label.sizePolicy().hasHeightForWidth())
        self.site_05_label.setSizePolicy(sizePolicy)
        self.site_05_label.setOpenExternalLinks(True)
        self.site_05_label.setObjectName(_fromUtf8("site_05_label"))
        self.site_06_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_06_label.setGeometry(QtCore.QRect(15, 110, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_06_label.sizePolicy().hasHeightForWidth())
        self.site_06_label.setSizePolicy(sizePolicy)
        self.site_06_label.setOpenExternalLinks(True)
        self.site_06_label.setObjectName(_fromUtf8("site_06_label"))
        self.site_07_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_07_label.setGeometry(QtCore.QRect(15, 140, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_07_label.sizePolicy().hasHeightForWidth())
        self.site_07_label.setSizePolicy(sizePolicy)
        self.site_07_label.setOpenExternalLinks(True)
        self.site_07_label.setObjectName(_fromUtf8("site_07_label"))
        self.site_08_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_08_label.setGeometry(QtCore.QRect(15, 170, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_08_label.sizePolicy().hasHeightForWidth())
        self.site_08_label.setSizePolicy(sizePolicy)
        self.site_08_label.setOpenExternalLinks(True)
        self.site_08_label.setObjectName(_fromUtf8("site_08_label"))
        self.site_09_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_09_label.setGeometry(QtCore.QRect(15, 200, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_09_label.sizePolicy().hasHeightForWidth())
        self.site_09_label.setSizePolicy(sizePolicy)
        self.site_09_label.setOpenExternalLinks(True)
        self.site_09_label.setObjectName(_fromUtf8("site_09_label"))
        self.site_11_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_11_label.setGeometry(QtCore.QRect(15, 230, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_11_label.sizePolicy().hasHeightForWidth())
        self.site_11_label.setSizePolicy(sizePolicy)
        self.site_11_label.setOpenExternalLinks(True)
        self.site_11_label.setObjectName(_fromUtf8("site_11_label"))
        self.site_12_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_12_label.setGeometry(QtCore.QRect(15, 260, 141, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_12_label.sizePolicy().hasHeightForWidth())
        self.site_12_label.setSizePolicy(sizePolicy)
        self.site_12_label.setOpenExternalLinks(True)
        self.site_12_label.setObjectName(_fromUtf8("site_12_label"))
        self.site_04_label = QtGui.QLabel(self.linkler_groupBox)
        self.site_04_label.setGeometry(QtCore.QRect(15, 50, 270, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.site_04_label.sizePolicy().hasHeightForWidth())
        self.site_04_label.setSizePolicy(sizePolicy)
        self.site_04_label.setOpenExternalLinks(True)
        self.site_04_label.setObjectName(_fromUtf8("site_04_label"))
        self.pushButton_android = QtGui.QPushButton(self.linkler_groupBox)
        self.pushButton_android.setGeometry(QtCore.QRect(170, 260, 21, 21))
        self.pushButton_android.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("C:/android.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_android.setIcon(icon4)
        self.pushButton_android.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_android.setFlat(True)
        self.pushButton_android.setObjectName(_fromUtf8("pushButton_android"))
        self.pushButton_ios = QtGui.QPushButton(self.linkler_groupBox)
        self.pushButton_ios.setGeometry(QtCore.QRect(200, 260, 21, 21))
        self.pushButton_ios.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("C:/ios.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ios.setIcon(icon5)
        self.pushButton_ios.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_ios.setFlat(True)
        self.pushButton_ios.setObjectName(_fromUtf8("pushButton_ios"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/resimler/linkler.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.linkler_tab, icon6, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 351, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDosya = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.menuDosya.setFont(font)
        self.menuDosya.setObjectName(_fromUtf8("menuDosya"))
        self.menuYardim = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.menuYardim.setFont(font)
        self.menuYardim.setObjectName(_fromUtf8("menuYardim"))
        self.menuGorunum = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuGorunum.setFont(font)
        self.menuGorunum.setObjectName(_fromUtf8("menuGorunum"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLisans = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionLisans.setFont(font)
        self.actionLisans.setObjectName(_fromUtf8("actionLisans"))
        self.actionHakkinda = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionHakkinda.setFont(font)
        self.actionHakkinda.setObjectName(_fromUtf8("actionHakkinda"))
        self.actionQtHakkinda = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionQtHakkinda.setFont(font)
        self.actionQtHakkinda.setObjectName(_fromUtf8("actionQtHakkinda"))
        self.actionCikis = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/resimler/cikis.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCikis.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionCikis.setFont(font)
        self.actionCikis.setIconVisibleInMenu(True)
        self.actionCikis.setObjectName(_fromUtf8("actionCikis"))
        self.actionWindowsVista = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionWindowsVista.setFont(font)
        self.actionWindowsVista.setObjectName(_fromUtf8("actionWindowsVista"))
        self.actionCleanlooks = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionCleanlooks.setFont(font)
        self.actionCleanlooks.setObjectName(_fromUtf8("actionCleanlooks"))
        self.actionPlastique = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionPlastique.setFont(font)
        self.actionPlastique.setObjectName(_fromUtf8("actionPlastique"))
        self.actionWindowsXP = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.actionWindowsXP.setFont(font)
        self.actionWindowsXP.setObjectName(_fromUtf8("actionWindowsXP"))
        self.menuDosya.addAction(self.actionCikis)
        self.menuYardim.addAction(self.actionLisans)
        self.menuYardim.addSeparator()
        self.menuYardim.addAction(self.actionHakkinda)
        self.menuYardim.addAction(self.actionQtHakkinda)
        self.menuGorunum.addAction(self.actionCleanlooks)
        self.menuGorunum.addAction(self.actionPlastique)
        self.menuGorunum.addSeparator()
        self.menuGorunum.addAction(self.actionWindowsXP)
        self.menuGorunum.addAction(self.actionWindowsVista)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuGorunum.menuAction())
        self.menubar.addAction(self.menuYardim.menuAction())
        
        self.actionVakitleriGoster = QtGui.QAction(MainWindow)
        self.actionVakitleriGoster.setIcon(icon)
        self.actionVakitleriGoster.setFont(font)
        self.actionVakitleriGoster.setIconVisibleInMenu(True)
        self.actionVakitleriGoster.setObjectName("actionVakitleriGoster")
                
        self.trayIcon = QtGui.QSystemTrayIcon(self)
        menu = QtGui.QMenu(self)
        menu.addAction(self.actionVakitleriGoster)
        menu.addAction(self.actionCikis)
        self.trayIcon.setContextMenu(menu)
        self.trayIcon.setIcon(QtGui.QIcon(":resimler/cami.png"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyVakitci", None))
        self.ulke_label.setText(_translate("MainWindow", "...", None))
        self.sehir_label.setText(_translate("MainWindow", "...", None))
        self.miladi_tarih.setText(_translate("MainWindow", "...", None))
        self.hicri_tarih.setText(_translate("MainWindow", "...", None))
        self.saat_label.setText(_translate("MainWindow", "...", None))
        self.namaz_vakti_label.setText(_translate("MainWindow", "...", None))
        self.imsak_label.setText(_translate("MainWindow", "İmsak", None))
        self.gunes_label.setText(_translate("MainWindow", "Güneş", None))
        self.ogle_label.setText(_translate("MainWindow", "Öğle", None))
        self.ikindi_label.setText(_translate("MainWindow", "İkindi", None))
        self.aksam_label.setText(_translate("MainWindow", "Akşam", None))
        self.yatsi_label.setText(_translate("MainWindow", "Yatsı", None))
        self.nokta_label.setText(_translate("MainWindow", ":", None))
        self.nokta_label_2.setText(_translate("MainWindow", ":", None))
        self.nokta_label_3.setText(_translate("MainWindow", ":", None))
        self.nokta_label_4.setText(_translate("MainWindow", ":", None))
        self.nokta_label_5.setText(_translate("MainWindow", ":", None))
        self.nokta_label_6.setText(_translate("MainWindow", ":", None))
        self.imsak_saat_label.setText(_translate("MainWindow", "...", None))
        self.gunes_saat_label.setText(_translate("MainWindow", "...", None))
        self.ogle_saat_label.setText(_translate("MainWindow", "...", None))
        self.ikindi_saat_label.setText(_translate("MainWindow", "...", None))
        self.aksam_saat_label.setText(_translate("MainWindow", "...", None))
        self.yatsi_saat_label.setText(_translate("MainWindow", "...", None))
        self.sonraki_vakit_label.setText(_translate("MainWindow", "...", None))
        self.kalan_sure_label.setText(_translate("MainWindow", "...", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.pyvakitci_tab), _translate("MainWindow", "Namaz Vakitleri", None))
        self.bolgesel_ayarlar_groupBox.setTitle(_translate("MainWindow", "Bölgesel Ayarlar", None))
        self.bolgesel_ayarlar_ulke_label.setText(_translate("MainWindow", "Ülke :", None))
        self.bolgesel_ayarlar_sehir_label.setText(_translate("MainWindow", "Şehir :", None))
        self.bolgesel_ayarlar_kaydet_pushButton.setToolTip(_translate("MainWindow", "Program kapanıp açıldığında yaptığınız değişikliklerin\n"
"hatırlanması için buraya tıklayın.", None))
        self.bolgesel_ayarlar_kaydet_pushButton.setText(_translate("MainWindow", "Kaydet", None))
        self.bolgesel_ayarlar_varsayilan_pushButton.setToolTip(_translate("MainWindow", "Varsayılan ayarlara dönmek isterseniz buraya tıklayın.", None))
        self.bolgesel_ayarlar_varsayilan_pushButton.setText(_translate("MainWindow", "Varsayılan", None))
        self.bolgesel_ayarlar_ilce_label.setText(_translate("MainWindow", "İlçe :", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.bolgesel_ayarlar_tab), _translate("MainWindow", "Bölgesel Ayarlar", None))
        self.ayarlar_groupBox.setTitle(_translate("MainWindow", "Ayarlar", None))
        self.otomatik_calistir_checkBox.setText(_translate("MainWindow", "Açılışta programı otomatik çalıştır", None))
        self.her_zaman_ustte_checkBox.setText(_translate("MainWindow", "Her zaman üstte göster", None))
        self.erken_uyari_checkBox.setText(_translate("MainWindow", "Vakit girmeden önce uyar (dk) :", None))
        self.ayarlar_kaydet_pushButton.setToolTip(_translate("MainWindow", "Program kapanıp açıldığında yaptığınız değişikliklerin\n"
"hatırlanması için buraya tıklayın.", None))
        self.ayarlar_kaydet_pushButton.setText(_translate("MainWindow", "Kaydet", None))
        self.ayarlar_varsayilan_pushButton.setToolTip(_translate("MainWindow", "Varsayılan ayarlara dönmek isterseniz buraya tıklayın.", None))
        self.ayarlar_varsayilan_pushButton.setText(_translate("MainWindow", "Varsayılan", None))
        self.besmele_ile_basla_checkBox.setText(_translate("MainWindow", "Besmele ile başla", None))
        self.otomatik_guncellestir_checkBox.setText(_translate("MainWindow", "Güncellemeleri kontrol et", None))
        self.sistem_tepsisinde_baslat_checkBox.setText(_translate("MainWindow", "Programı sistem tepsisinde başlat", None))
        self.vakitleri_goster_pushButton.setText(_translate("MainWindow", " Vakitleri aylık olarak göster", None))
        self.vakitleri_guncelle_pushButton.setText(_translate("MainWindow", "Aylık vakitleri şimdi güncelle", None))
        self.erken_uyari_sela_checkBox.setText(_translate("MainWindow", "Selayı vakit girmeden oku (dk) :", None))
        self.hicri_gun_ekle_checkBox.setToolTip(_translate("MainWindow", "Hicri tarihteki gecikmeyi önlemek için kullanabilirsiniz. Ayda bir hicri tarihi başka kaynaktan kontrol etmek gerekebilir.", None))
        self.hicri_gun_ekle_checkBox.setText(_translate("MainWindow", "Hicri tarihe gün ilave et :", None))
        self.ikon_goster_checkBox.setToolTip(_translate("MainWindow", "Aktif değilse program çarpıya tıklandığında kapanır.", None))
        self.ikon_goster_checkBox.setText(_translate("MainWindow", "Sistem tepsisinde ikon göster.", None))
        self.winamp_duraklat_checkBox.setText(_translate("MainWindow", "Winamp\'ta çalan şarkıyı duraklat.", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.ayarlar_tab), _translate("MainWindow", "Genel Ayarlar", None))
        self.sabah_ses_label.setText(_translate("MainWindow", "Sabah :", None))
        self.sabah_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.dua_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.dua_ses_label.setText(_translate("MainWindow", "Dua :", None))
        self.aksam_ses_label.setText(_translate("MainWindow", "Akşam :", None))
        self.aksam_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.uyari_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.yatsi_ses_label.setText(_translate("MainWindow", "Yatsı :", None))
        self.yatsi_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.uyari_ses_label.setText(_translate("MainWindow", "Uyarı :", None))
        self.ogle_ses_label.setText(_translate("MainWindow", "Öğle :", None))
        self.ogle_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.ikindi_ses_label.setText(_translate("MainWindow", "İkindi :", None))
        self.ikindi_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.ses_kaydet_pushButton.setToolTip(_translate("MainWindow", "Program kapanıp açıldığında yaptığınız değişikliklerin\n"
"hatırlanması için buraya tıklayın.", None))
        self.ses_kaydet_pushButton.setText(_translate("MainWindow", "Kaydet", None))
        self.ses_varsayilan_pushButton.setToolTip(_translate("MainWindow", "Varsayılan ayarlara dönmek isterseniz buraya tıklayın.", None))
        self.ses_varsayilan_pushButton.setText(_translate("MainWindow", "Varsayılan", None))
        self.sela_ses_label.setText(_translate("MainWindow", "Sela :", None))
        self.sela_toolButton.setText(_translate("MainWindow", "Ekle", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.ses_dosyalari_tab), _translate("MainWindow", "Ses Dosyaları", None))
        self.linkler_groupBox.setTitle(_translate("MainWindow", "Yararlı Siteler", None))
        self.site_01_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.sorularlaislamiyet.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">Sorularla İslamiyet</span></a></p></body></html>", None))
        self.site_05_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://kuran.diyanet.gov.tr\"><span style=\" text-decoration: underline; color:#0000ff;\">Diyanet Kur\'an Eğitimi</span></a></p></body></html>", None))
        self.site_06_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://kuran.diyanet.gov.tr/mushaf\"><span style=\" text-decoration: underline; color:#0000ff;\">Diyanet (Kur\'an-ı Kerim ve Meâli)</span></a></p></body></html>", None))
        self.site_07_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://tanzil.net\"><span style=\" text-decoration: underline; color:#0000ff;\">Tanzil (Kur\'an-ı Kerim ve Meâli)</span></a></p></body></html>", None))
        self.site_08_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://hadis.resulullah.org\"><span style=\" text-decoration: underline; color:#0000ff;\">Kütüb-ü Sitte | İbrahim Canan</span></a></p></body></html>", None))
        self.site_09_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.hadis.gen.tr/\"><span style=\" text-decoration: underline; color:#0000ff;\">Hadis.gen.tr</span></a></p></body></html>", None))
        self.site_11_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www2.diyanet.gov.tr/DinHizmetleriGenelMudurlugu/Sayfalar/2021DiniG%C3%BCnlerListesi.aspx\"><span style=\" text-decoration: underline; color:#0000ff;\">Dini Günler ve Geceler</span></a></p></body></html>", None))
        self.site_12_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.erisale.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">Risale-i Nur Külliyatı</span></a></p></body></html>", None))
        self.site_04_label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.kurantv.net\"><span style=\" text-decoration: underline; color:#0000ff;\">Kuran.tv</span></a></p></body></html>", None))
        self.pushButton_android.setToolTip(_translate("MainWindow", "Anroid için Risale-i Nur", None))
        self.pushButton_ios.setToolTip(_translate("MainWindow", "iPhone için Risale-i Nur", None))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.linkler_tab), _translate("MainWindow", "Yararlı Siteler", None))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya", None))
        self.menuYardim.setTitle(_translate("MainWindow", "Yardım", None))
        self.menuGorunum.setTitle(_translate("MainWindow", "Görünüm", None))
        self.actionLisans.setText(_translate("MainWindow", "Lisans", None))
        self.actionHakkinda.setText(_translate("MainWindow", "Hakkında", None))
        self.actionQtHakkinda.setText(_translate("MainWindow", "Qt Hakkında", None))
        self.actionCikis.setText(_translate("MainWindow", "Çıkış", None))
        self.actionCikis.setShortcut(_translate("MainWindow", "Esc", None))
        self.actionWindowsVista.setText(_translate("MainWindow", "Windows Vista", None))
        self.actionCleanlooks.setText(_translate("MainWindow", "Cleanlooks", None))
        self.actionPlastique.setText(_translate("MainWindow", "Plastique", None))
        self.actionWindowsXP.setText(_translate("MainWindow", "Windows XP", None))
        self.actionVakitleriGoster.setText(_translate("MainWindow", "Vakitleri Göster", None))